# POP Website Load Test Configuration
# Updated with latest features - 2-minute Azure distributed test
# Technical analysis only (no AI insights)

target: https://wearepop.com
vus: 20  # 20 virtual users for Azure test
duration: 5m  # 5-minute test
test_type: both  # Run both protocol and browser tests

# Site description
description: "Frontend is built with Svelte and the Backend is built with Strapi. The frontend application gets its data from the strapi api. This app is an App Service that lives on azure."

# Technology tags for analysis
tags:
  - "svelte"
  - "strapi"
  - "azure"
  - "app-service"
  - "headless-cms"
  - "javascript"
  - "api-driven"
  - "pop-website"
  - "comprehensive-test"

# Analysis settings - Technical only, no AI
analysis_settings:
  run_page_resource_analysis: true
  run_enhanced_performance_analysis: true
  run_ai_analysis: false  # Disabled for technical analysis only
  generate_readable_reports: true
  combine_results: true

# Protocol test settings (k6)
protocol_settings:
  vus: 20  # 20 virtual users for Azure test
  duration: 5m
  thresholds:
    http_req_duration: ['p(95)<10000']  # Increased to 10s for high load
    http_req_failed: ['rate<0.3']       # Increased error rate tolerance for ramp-up

# Browser test settings (xk6-browser) - Enabled for both tests
browser_settings:
  vus: 10  # 10 virtual users for browser test
  duration: 5m  # 2-minute browser test
  viewport:
    width: 1920
    height: 1080
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  wait_until: "networkidle"
  timeout: "30s"

# Performance thresholds for browser metrics
browser_thresholds:
  first_contentful_paint: 1800  # 1.8s
  largest_contentful_paint: 2500  # 2.5s
  first_input_delay: 100  # 100ms
  cumulative_layout_shift: 0.1
  time_to_interactive: 3800  # 3.8s
  dom_content_loaded: 2000  # 2s
  load_complete: 3000  # 3s

# User interaction simulation
user_interactions:
  enabled: true
  click_elements: true
  scroll_page: true
  wait_between_actions: 1000  # ms

# Azure Distributed Testing Configuration
azure:
  subscription_id: "73680a18-9795-402d-bfa2-fd739ae160c1"
  resource_group: "POP-Tools"
  location: "eastus"
  storage_account: "poploadteststorage"
  container_name: "results"
  container_registry: "poploadtestregistry.azurecr.io"

# Distribution settings for Azure distributed testing - Both test types enabled
distribution:
  total_vus: 20  # Total VUs across all workers
  duration: "5m"  # Test duration
  vus_per_container:
    protocol: 10  # VUs per protocol worker container
    browser: 5    # VUs per browser worker container
  resources:
    protocol:
      cpu: 1.0
      memory: 2.0
    browser:
      cpu: 2.0
      memory: 4.0 