# POP Website 30-Minute Azure Distributed Test
# Comprehensive 30-minute load test with AI analysis

target: https://wearepop.com
test_type: both  # Run both protocol and browser tests

# Site description
description: "Frontend is built with Svelte and the Backend is built with Strapi. The frontend application gets its data from the strapi api. This app is an App Service that lives on azure."

# Technology tags for analysis
tags:
  - "svelte"
  - "strapi"
  - "azure"
  - "app-service"
  - "headless-cms"
  - "javascript"
  - "api-driven"
  - "pop-website"
  - "30min-test"

# Analysis settings - Enable AI analysis for comprehensive insights
analysis_settings:
  run_page_resource_analysis: true
  run_enhanced_performance_analysis: true
  run_ai_analysis: true  # Enable AI analysis
  generate_readable_reports: true
  combine_results: true

# Azure Configuration - REQUIRED for distributed testing
azure:
  subscription_id: "73680a18-9795-402d-bfa2-fd739ae160c1"
  resource_group: "POP-Tools"
  location: "eastus"
  storage_account: "poploadteststorage"
  container_name: "results"
  container_registry: "poploadtestregistry.azurecr.io"

# Distribution settings for Azure distributed testing - 30-minute comprehensive test
distribution:
  total_vus: 60   # Total VUs across all workers (higher load for 30min test)
  duration: "30m"  # 30-minute comprehensive test
  vus_per_container:
    protocol: 15   # VUs per protocol worker container (4 containers × 15 = 60)
    browser: 3     # VUs per browser worker container (1 container × 3 = 3)
  resources:
    protocol:
      cpu: 1.0
      memory: 2.0
    browser:
      cpu: 2.0     # Higher CPU for browser tests
      memory: 4.0  # Higher memory for browser tests

# Load test stages for realistic ramp-up/ramp-down
stages:
  protocol:
    - duration: "5m"   # Warm-up phase
      target: 15       # Gradually ramp to 15 VUs per container
    - duration: "20m"  # Sustained load phase
      target: 15       # Maintain 15 VUs per container
    - duration: "5m"   # Cool-down phase
      target: 0        # Gradually reduce to 0
  browser:
    - duration: "5m"   # Warm-up phase
      target: 1        # Gradually ramp to 1 VU per container
    - duration: "20m"  # Sustained load phase
      target: 3        # Maintain 3 VUs per container
    - duration: "5m"   # Cool-down phase
      target: 0        # Gradually reduce to 0

# Protocol test settings (k6) - 30-minute comprehensive test
protocol_settings:
  thresholds:
    http_req_duration: ['p(95)<5000']  # 5s threshold for 30min test
    http_req_failed: ['rate<0.1']      # 10% error rate tolerance for 30min test
    http_reqs: ['rate>50']             # Minimum 50 req/s throughput

# Browser test settings (xk6-browser) - 30-minute comprehensive test
browser_settings:
  viewport:
    width: 1920
    height: 1080
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  wait_until: "networkidle"
  timeout: "45s"  # Increased timeout for 30min test

# Performance thresholds for browser metrics
browser_thresholds:
  first_contentful_paint: 1800  # 1.8s
  largest_contentful_paint: 2500  # 2.5s
  first_input_delay: 100  # 100ms
  cumulative_layout_shift: 0.1
  time_to_interactive: 3800  # 3.8s
  dom_content_loaded: 2000  # 2s
  load_complete: 3000  # 3s

# User interaction simulation - Enhanced for 30-minute test
user_interactions:
  enabled: true
  click_elements: true
  scroll_page: true
  wait_between_actions: 2000  # Increased to 2s for realistic user behavior
  random_delays: true  # Add random delays between 1-3 seconds
  simulate_reading: true  # Simulate users reading content
