# POP Website Load Test Configuration
# Updated with latest features - 30-minute comprehensive Azure distributed test
# Enhanced AI analysis enabled

target: https://wearepop.com
vus: 10  # 10 virtual users for 2-minute test
duration: 2m  # 2-minute test
test_type: both  # Run both protocol and browser tests

# Site description
description: "Frontend is built with Svelte and the Backend is built with Strapi. The frontend application gets its data from the strapi api. This app is an App Service that lives on azure."

# Technology tags for analysis
tags:
  - "svelte"
  - "strapi"
  - "azure"
  - "app-service"
  - "headless-cms"
  - "javascript"
  - "api-driven"

# Analysis settings - Technical only, no AI
analysis_settings:
  run_page_resource_analysis: true
  run_enhanced_performance_analysis: true
  run_ai_analysis: true  # Enable enhanced AI analysis


# Protocol test settings (k6) - 30-minute comprehensive test
protocol_settings:
  vus: 8   # 8 virtual users for 2-minute test
  duration: 2m
  stages:
    - duration: "30s"  # Warm-up phase
      target: 5        # Gradually ramp to 5 VUs
    - duration: "1m"   # Sustained load phase
      target: 8        # Maintain 8 VUs
    - duration: "30s"  # Cool-down phase
      target: 0        # Gradually reduce to 0
  thresholds:
    http_req_duration: ['p(95)<5000']   # 5s threshold for 30-min test
    http_req_failed: ['rate<0.1']       # 10% error rate tolerance
    http_reqs: ['rate>10']              # Minimum 10 req/s throughput

# Browser test settings (Playwright) - 30-minute comprehensive test
browser_settings:
  vus: 2   # 2 virtual users for 2-minute browser test
  duration: 2m
  stages:
    - duration: "30s"  # Warm-up phase
      target: 1        # Gradually ramp to 1 VU
    - duration: "1m"   # Sustained load phase
      target: 2        # Maintain 2 VUs
    - duration: "30s"  # Cool-down phase
      target: 0        # Gradually reduce to 0
  viewport:
    width: 1920
    height: 1080
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  wait_until: "networkidle"
  timeout: "45s"  # Increased timeout for 30-min test

# Performance thresholds for browser metrics
browser_thresholds:
  first_contentful_paint: 1800  # 1.8s
  largest_contentful_paint: 2500  # 2.5s
  first_input_delay: 100  # 100ms
  cumulative_layout_shift: 0.1
  time_to_interactive: 3800  # 3.8s
  dom_content_loaded: 2000  # 2s
  load_complete: 3000  # 3s

# User interaction simulation - Enhanced for 30-minute test
user_interactions:
  enabled: true
  click_elements: true
  scroll_page: true
  wait_between_actions: 2000  # Increased to 2s for realistic user behavior
  random_delays: true  # Add random delays between 1-3 seconds
  simulate_reading: true  # Simulate users reading content

# Azure Distributed Testing Configuration
azure:
  subscription_id: "73680a18-9795-402d-bfa2-fd739ae160c1"
  resource_group: "POP-Tools"
  location: "eastus"
  storage_account: "poploadteststorage"
  container_name: "results"
  container_registry: "poploadtestregistry.azurecr.io"

# Distribution settings for Azure distributed testing - 30-minute comprehensive test
distribution:
  total_vus: 10   # Total VUs across all workers (8 protocol + 2 browser)
  duration: "2m"  # 2-minute test duration
  vus_per_container:
    protocol: 4   # VUs per protocol worker container (2 containers × 4 = 8)
    browser: 2    # VUs per browser worker container (1 container × 2 = 2)
  resources:
    protocol:
      cpu: 1.0    # Reduced CPU to fit quota
      memory: 2.0 # Reduced memory to fit quota
    browser:
      cpu: 1.0    # Reduced CPU to fit quota
      memory: 2.0 # Reduced memory to fit quota 