# Technical Analysis Configuration
# Runs comprehensive technical analysis without AI insights
# Perfect for debugging, cost optimization, or technical-only analysis

target: https://pop-website-2024-dev.azurewebsites.net
vus: 10  # Protocol test VUs
duration: 3m  # Test duration
test_type: both  # Run both protocol and browser tests

# Site description
description: "Frontend is built with Svelte and the Backend is built with Strapi. Technical analysis without AI insights."

# Technology tags
tags:
  - "svelte"
  - "strapi"
  - "azure"
  - "app-service"
  - "headless-cms"
  - "javascript"
  - "api-driven"
  - "technical-analysis"
  - "no-ai"

# Analysis settings - Technical only, no AI
analysis_settings:
  run_page_resource_analysis: true
  run_enhanced_performance_analysis: true
  run_ai_analysis: false  # Skip AI analysis
  generate_readable_reports: true
  combine_results: true

# Protocol test settings (k6)
protocol_settings:
  vus: 10  # Higher VUs for protocol testing
  duration: 3m
  thresholds:
    http_req_duration: ['p(95)<2000']  # 95% under 2s
    http_req_failed: ['rate<0.1']      # Error rate under 10%

# Browser test settings (xk6-browser)
browser_settings:
  vus: 3  # Lower VUs for browser testing (resource-intensive)
  duration: 2m  # Shorter duration for browser tests
  viewport:
    width: 1920
    height: 1080
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  wait_until: "networkidle"
  timeout: "30s"

# Performance thresholds for browser metrics
browser_thresholds:
  first_contentful_paint: 1800  # 1.8s
  largest_contentful_paint: 2500  # 2.5s
  first_input_delay: 100  # 100ms
  cumulative_layout_shift: 0.1
  time_to_interactive: 3800  # 3.8s
  dom_content_loaded: 2000  # 2s
  load_complete: 3000  # 3s

# User interaction simulation
user_interactions:
  enabled: true
  click_elements: true
  scroll_page: true
  wait_between_actions: 1000  # ms
