# Load Test Configuration
# Target URL to test (can be any web application: AEM, WordPress, React, etc.)
target: https://example.com/contact

# Number of virtual users (concurrent users)
vus: 50

# Test duration (supports: 30s, 1m, 5m, 1h, etc.)
duration: 30s

# Site description for AI analysis (optional)
description: "Example website for load testing"

# Tags for categorization and AI analysis (optional)
tags:
  - "example"
  - "contact-form"
  - "static-site"

# Optional: Additional configuration options
# These can be extended in future phases
# timeout: 10s
# ramp_up: 10s
# think_time: 1s
