# WordPress Load Test Configuration
# Example configuration for testing WordPress sites

# Target WordPress site
target: https://wordpress.org/

# Moderate load test
vus: 25
duration: 2m

# Site description for AI analysis
description: "Official WordPress.org website - a popular content management system built with PHP"

# Tags for categorization and AI analysis
tags:
  - "wordpress"
  - "php"
  - "cms"
  - "content-management"
  - "open-source"

# Optional: Additional configuration options
# These can be extended in future phases
# timeout: 10s
# ramp_up: 10s
# think_time: 1s 