# GitHub Pages Configuration
title: Load Testing & Optimization Agent
description: Automated load testing with AI-powered performance optimization recommendations
url: "https://colespicer.github.io"
baseurl: "/load-opt-agent"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 